[2016-06-07 13:43:55] lumen.ERROR: exception 'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, class 'Nord\Lumen\Cors\CorsFacade' does not have a method 'handle'' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php:136
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'call_user_func_...', 'C:\\xampp1\\htdoc...', 136, Array)
#1 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 C:\xampp1\htdocs\Lumen_API\app\Http\Middleware\Authenticate.php(41): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#5 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#6 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(482): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#13 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#14 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#15 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 C:\xampp1\htdocs\Lumen_API\vendor\nordsoftware\lumen-cors\src\CorsMiddleware.php(45): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Nord\Lumen\Cors\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#25 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#26 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#27 {main}  
[2016-06-07 13:44:56] lumen.ERROR: exception 'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, class 'Nord\Lumen\Cors\CorsFacade' does not have a method 'handle'' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php:136
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'call_user_func_...', 'C:\\xampp1\\htdoc...', 136, Array)
#1 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 C:\xampp1\htdocs\Lumen_API\app\Http\Middleware\Authenticate.php(41): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#5 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#6 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(482): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#13 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#14 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#15 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 C:\xampp1\htdocs\Lumen_API\vendor\nordsoftware\lumen-cors\src\CorsMiddleware.php(38): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Nord\Lumen\Cors\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#25 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#26 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#27 {main}  
[2016-06-07 13:46:41] lumen.ERROR: exception 'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, class 'Nord\Lumen\Cors\CorsFacade' does not have a method 'handle'' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php:136
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'call_user_func_...', 'C:\\xampp1\\htdoc...', 136, Array)
#1 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 C:\xampp1\htdocs\Lumen_API\app\Http\Middleware\Authenticate.php(41): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#5 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#6 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(482): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#13 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#14 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(636): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#15 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#16 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#17 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#18 {main}  
[2016-06-07 13:46:42] lumen.ERROR: exception 'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, class 'Nord\Lumen\Cors\CorsFacade' does not have a method 'handle'' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php:136
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'call_user_func_...', 'C:\\xampp1\\htdoc...', 136, Array)
#1 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 C:\xampp1\htdocs\Lumen_API\app\Http\Middleware\Authenticate.php(41): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#5 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#6 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(482): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#13 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#14 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(636): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#15 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#16 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#17 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#18 {main}  
[2016-06-07 13:47:01] lumen.ERROR: exception 'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, class 'Nord\Lumen\Cors\CorsFacade' does not have a method 'handle'' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php:136
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'call_user_func_...', 'C:\\xampp1\\htdoc...', 136, Array)
#1 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 C:\xampp1\htdocs\Lumen_API\app\Http\Middleware\Authenticate.php(41): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#5 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#6 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(482): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#13 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#14 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(636): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#15 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#16 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#17 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#18 {main}  
[2016-06-07 13:47:14] lumen.ERROR: exception 'ReflectionException' with message 'Class cors does not exist' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\container\Container.php:738
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\container\Container.php(738): ReflectionClass->__construct('cors')
#1 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\container\Container.php(633): Illuminate\Container\Container->build('cors', Array)
#2 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Application.php(205): Illuminate\Container\Container->make('cors', Array)
#3 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(126): Laravel\Lumen\Application->make('cors')
#4 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#5 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#6 C:\xampp1\htdocs\Lumen_API\app\Http\Middleware\Authenticate.php(41): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#7 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#8 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#12 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(482): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#15 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#16 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(636): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#17 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#18 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#19 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#20 {main}  
[2016-06-07 13:47:17] lumen.ERROR: exception 'ReflectionException' with message 'Class cors does not exist' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\container\Container.php:738
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\container\Container.php(738): ReflectionClass->__construct('cors')
#1 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\container\Container.php(633): Illuminate\Container\Container->build('cors', Array)
#2 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Application.php(205): Illuminate\Container\Container->make('cors', Array)
#3 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(126): Laravel\Lumen\Application->make('cors')
#4 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#5 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#6 C:\xampp1\htdocs\Lumen_API\app\Http\Middleware\Authenticate.php(41): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#7 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#8 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#12 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(482): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#15 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#16 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(636): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#17 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#18 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#19 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#20 {main}  
[2016-06-07 13:47:38] lumen.ERROR: exception 'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, class 'Nord\Lumen\Cors\CorsFacade' does not have a method 'handle'' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php:136
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'call_user_func_...', 'C:\\xampp1\\htdoc...', 136, Array)
#1 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 C:\xampp1\htdocs\Lumen_API\app\Http\Middleware\Authenticate.php(41): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#5 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#6 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(482): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#13 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#14 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#15 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 C:\xampp1\htdocs\Lumen_API\vendor\nordsoftware\lumen-cors\src\CorsMiddleware.php(38): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Nord\Lumen\Cors\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#25 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#26 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#27 {main}  
[2016-06-07 13:49:22] lumen.ERROR: exception 'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, class 'Nord\Lumen\Cors\CorsFacade' does not have a method 'handle'' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php:136
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'call_user_func_...', 'C:\\xampp1\\htdoc...', 136, Array)
#1 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 C:\xampp1\htdocs\Lumen_API\app\Http\Middleware\Authenticate.php(41): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#5 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#6 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(482): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#13 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#14 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#15 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 C:\xampp1\htdocs\Lumen_API\vendor\nordsoftware\lumen-cors\src\CorsMiddleware.php(38): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Nord\Lumen\Cors\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#25 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#26 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#27 {main}  
[2016-06-07 13:49:23] lumen.ERROR: exception 'ErrorException' with message 'call_user_func_array() expects parameter 1 to be a valid callback, class 'Nord\Lumen\Cors\CorsFacade' does not have a method 'handle'' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php:136
Stack trace:
#0 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(2, 'call_user_func_...', 'C:\\xampp1\\htdoc...', 136, Array)
#1 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 C:\xampp1\htdocs\Lumen_API\app\Http\Middleware\Authenticate.php(41): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#5 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#6 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(482): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#13 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#14 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#15 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 C:\xampp1\htdocs\Lumen_API\vendor\nordsoftware\lumen-cors\src\CorsMiddleware.php(38): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Nord\Lumen\Cors\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#25 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#26 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#27 {main}  
[2016-06-08 12:00:49] lumen.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Memcached' not found' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\cache\MemcachedConnector.php:51
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main}  
[2016-06-08 17:05:08] lumen.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Illuminate\Mail\MailServiceProvider' not found' in C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Application.php:162
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main}  
[2016-06-08 17:07:45] lumen.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Illuminate\Mail\MailServiceProvider' not found' in C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Application.php:162
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main}  
[2016-06-08 17:08:52] lumen.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Illuminate\Mail\MailServiceProvider' not found' in C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Application.php:162
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main}  
[2016-06-08 17:12:18] lumen.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Illuminate\Mail\MailServiceProvider' not found' in C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Application.php:162
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main}  
[2016-06-08 17:12:20] lumen.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Illuminate\Mail\MailServiceProvider' not found' in C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Application.php:162
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main}  
[2016-06-08 17:25:18] lumen.ERROR: exception 'ErrorException' with message 'Argument 2 passed to Illuminate\Mail\Mailer::send() must be of the type array, object given, called in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\support\Facades\Facade.php on line 221 and defined' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\mail\Mailer.php:149
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\mail\Mailer.php(149): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(4096, 'Argument 2 pass...', 'C:\\xampp1\\htdoc...', 149, Array)
#1 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\support\Facades\Facade.php(221): Illuminate\Mail\Mailer->send('auth.reminder', Object(Closure))
#2 C:\xampp1\htdocs\Lumen_API\app\Http\routes.php(34): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#3 C:\xampp1\htdocs\Lumen_API\app\Http\routes.php(34): Illuminate\Support\Facades\Mail::send('auth.reminder', Object(Closure))
#4 [internal function]: Closure->{closure}()
#5 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\container\Container.php(507): call_user_func_array(Object(Closure), Array)
#6 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(512): Illuminate\Container\Container->call(Object(Closure), Array)
#7 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(486): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#8 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#9 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#10 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 C:\xampp1\htdocs\Lumen_API\vendor\nordsoftware\lumen-cors\src\CorsMiddleware.php(38): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#12 [internal function]: Nord\Lumen\Cors\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#17 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#20 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#21 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#22 {main}  
[2016-06-08 17:39:00] lumen.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Controller' not found' in C:\xampp1\htdocs\Lumen_API\app\Http\Controllers\recoveryController.php:5
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main}  
[2016-06-08 17:39:43] lumen.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\recoveryController does not exist' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\container\Container.php:738
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\container\Container.php(738): ReflectionClass->__construct('App\\Http\\Contro...')
#1 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\container\Container.php(633): Illuminate\Container\Container->build('App\\Http\\Contro...', Array)
#2 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Application.php(205): Illuminate\Container\Container->make('App\\Http\\Contro...', Array)
#3 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(528): Laravel\Lumen\Application->make('App\\Http\\Contro...')
#4 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(501): Laravel\Lumen\Application->callControllerAction(Array)
#5 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(486): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#6 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#7 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#8 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 C:\xampp1\htdocs\Lumen_API\vendor\nordsoftware\lumen-cors\src\CorsMiddleware.php(45): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Nord\Lumen\Cors\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#15 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#18 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#19 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#20 {main}  
[2016-06-08 17:47:12] lumen.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ';', expecting ')'' in C:\xampp1\htdocs\Lumen_API\app\Http\Controllers\recoveryController.php:12
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main}  
[2016-06-08 17:48:33] lumen.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\Validator' not found' in C:\xampp1\htdocs\Lumen_API\app\Http\Controllers\recoveryController.php:17
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main}  
[2016-06-08 17:57:09] lumen.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected end of file, expecting function (T_FUNCTION)' in C:\xampp1\htdocs\Lumen_API\app\Http\Controllers\recoveryController.php:49
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main}  
[2016-06-08 18:01:29] lumen.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\Hash' not found' in C:\xampp1\htdocs\Lumen_API\app\Http\Controllers\recoveryController.php:37
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main}  
[2016-06-08 18:06:26] lumen.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list'' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Connection.php:429
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Connection.php(429): PDO->prepare('update `users` ...')
#1 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Connection.php(673): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'update `users` ...', Array)
#2 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Connection.php(636): Illuminate\Database\Connection->runQueryCallback('update `users` ...', Array, Object(Closure))
#3 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Connection.php(434): Illuminate\Database\Connection->run('update `users` ...', Array, Object(Closure))
#4 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Connection.php(377): Illuminate\Database\Connection->affectingStatement('update `users` ...', Array)
#5 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Query\Builder.php(2033): Illuminate\Database\Connection->update('update `users` ...', Array)
#6 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Eloquent\Builder.php(517): Illuminate\Database\Query\Builder->update(Array)
#7 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Eloquent\Model.php(1555): Illuminate\Database\Eloquent\Builder->update(Array)
#8 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Eloquent\Model.php(1474): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder), Array)
#9 C:\xampp1\htdocs\Lumen_API\app\Http\Controllers\recoveryController.php(41): Illuminate\Database\Eloquent\Model->save()
#10 [internal function]: App\Http\Controllers\recoveryController->recovery(Object(Illuminate\Http\Request))
#11 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\container\Container.php(507): call_user_func_array(Array, Array)
#12 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(593): Illuminate\Container\Container->call(Array, Array)
#13 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(560): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#14 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(533): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\recoveryController), 'recovery', Array)
#15 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(501): Laravel\Lumen\Application->callControllerAction(Array)
#16 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(486): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#17 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#18 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#19 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 C:\xampp1\htdocs\Lumen_API\vendor\nordsoftware\lumen-cors\src\CorsMiddleware.php(45): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#21 [internal function]: Nord\Lumen\Cors\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#26 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#29 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#30 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#31 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'updated_at' in 'field list' (SQL: update `users` set `password_temp` = yMhXOMqqRYNXHof1oWk6beYO2kySRI9M0jtn2GQAvFciFko7FxL.a, `resetcode` = ZnlXDIvsUtQKlSLJZz1BxtMsTopl0VnUp7eijOVjhjROkvEKWLS08jjssXrV, `updated_at` = 2016-06-08 18:06:26 where `id` = 1)' in C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Connection.php:680
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Connection.php(636): Illuminate\Database\Connection->runQueryCallback('update `users` ...', Array, Object(Closure))
#1 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Connection.php(434): Illuminate\Database\Connection->run('update `users` ...', Array, Object(Closure))
#2 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Connection.php(377): Illuminate\Database\Connection->affectingStatement('update `users` ...', Array)
#3 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Query\Builder.php(2033): Illuminate\Database\Connection->update('update `users` ...', Array)
#4 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Eloquent\Builder.php(517): Illuminate\Database\Query\Builder->update(Array)
#5 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Eloquent\Model.php(1555): Illuminate\Database\Eloquent\Builder->update(Array)
#6 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\database\Eloquent\Model.php(1474): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder), Array)
#7 C:\xampp1\htdocs\Lumen_API\app\Http\Controllers\recoveryController.php(41): Illuminate\Database\Eloquent\Model->save()
#8 [internal function]: App\Http\Controllers\recoveryController->recovery(Object(Illuminate\Http\Request))
#9 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\container\Container.php(507): call_user_func_array(Array, Array)
#10 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(593): Illuminate\Container\Container->call(Array, Array)
#11 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(560): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#12 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(533): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\recoveryController), 'recovery', Array)
#13 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(501): Laravel\Lumen\Application->callControllerAction(Array)
#14 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(486): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#15 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#16 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#17 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 C:\xampp1\htdocs\Lumen_API\vendor\nordsoftware\lumen-cors\src\CorsMiddleware.php(45): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Nord\Lumen\Cors\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#21 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#24 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#27 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#28 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#29 {main}  
[2016-06-08 18:09:15] lumen.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Http\Controllers\URL' not found' in C:\xampp1\htdocs\Lumen_API\app\Http\Controllers\recoveryController.php:46
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RegistersExceptionHandlers.php(55): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main}  
[2016-06-08 18:09:43] lumen.ERROR: exception 'ErrorException' with message 'Undefined variable: email' in C:\xampp1\htdocs\Lumen_API\app\Http\Controllers\recoveryController.php:52
Stack trace:
#0 C:\xampp1\htdocs\Lumen_API\app\Http\Controllers\recoveryController.php(52): Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(8, 'Undefined varia...', 'C:\\xampp1\\htdoc...', 52, Array)
#1 [internal function]: App\Http\Controllers\recoveryController->App\Http\Controllers\{closure}(Object(Illuminate\Mail\Message))
#2 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\mail\Mailer.php(401): call_user_func(Object(Closure), Object(Illuminate\Mail\Message))
#3 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\mail\Mailer.php(165): Illuminate\Mail\Mailer->callMessageBuilder(Object(Closure), Object(Illuminate\Mail\Message))
#4 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\support\Facades\Facade.php(224): Illuminate\Mail\Mailer->send('auth.reminder', Array, Object(Closure))
#5 C:\xampp1\htdocs\Lumen_API\app\Http\Controllers\recoveryController.php(52): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#6 C:\xampp1\htdocs\Lumen_API\app\Http\Controllers\recoveryController.php(52): Illuminate\Support\Facades\Mail::send('auth.reminder', Array, Object(Closure))
#7 [internal function]: App\Http\Controllers\recoveryController->recovery(Object(Illuminate\Http\Request))
#8 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\container\Container.php(507): call_user_func_array(Array, Array)
#9 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(593): Illuminate\Container\Container->call(Array, Array)
#10 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(560): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#11 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(533): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\recoveryController), 'recovery', Array)
#12 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(501): Laravel\Lumen\Application->callControllerAction(Array)
#13 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(486): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#14 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(383): Laravel\Lumen\Application->handleFoundRoute(Array)
#15 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#16 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 C:\xampp1\htdocs\Lumen_API\vendor\nordsoftware\lumen-cors\src\CorsMiddleware.php(45): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#18 [internal function]: Nord\Lumen\Cors\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(136): call_user_func_array(Array, Array)
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 [internal function]: Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#23 C:\xampp1\htdocs\Lumen_API\vendor\illuminate\pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(633): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(389): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#26 C:\xampp1\htdocs\Lumen_API\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(334): Laravel\Lumen\Application->dispatch(Object(Illuminate\Http\Request))
#27 C:\xampp1\htdocs\Lumen_API\public\index.php(27): Laravel\Lumen\Application->run(Object(Illuminate\Http\Request))
#28 {main}  
